# Final project {#final_project -}

## Background

Your final project is an opportunity for you to produce a product that shows-off some of what you have learned in the course.

You may work alone or with up to two other students in the class.
If you work with others, you will need to complete a statement about who did what, and all of the members of your team will get the same grade.

## Topics

You may choose any of a wide range of topics for your final project:

- A tool or resource you find especially useful.
- A paper or papers that do or do not replicate.
- Independent research on some topic related to open science.

## Formats

There are multiple formats for your final project.

- Short (5-10 min) in-class talk
- Poster
- Lesson plan/exercise
- Tutorial
- Research project (& write-up)
- Opinion piece

## Components

- Project proposal
    - Every student or team must submit a one-page project proposal. If the proposal is submitted on-time (by Thu March 2), the student or team gets 5 extra credit points. If the proposal is submitted late, there is no penalty, but also no extra points. If a student or team does not submit a proposal, there will be a five point penalty.
- Project presentation (optional)
    - Every student or team may make an optional presentation to the class about their project.
    - The presentations will occur during class on April 25 and April 27.
- Project write-up
    - Every student or team must submit a write-up, due on May 3, 2023.
    - Depending on the format of the project (talk, poster, paper), different materials may be submitted (slides, poster, etc.).