# Schedule {-}

---

## January 9 - 13 {- #week-01}

### Tuesday, January 10 {-}

- Introduction to the course
- Read
    - [[@Feynman1974-ld]](https://calteches.library.caltech.edu/51/2/CargoCult.htm).
    - [@Harris2017-oz], Chapter 1, Begley's Bombshell. [PDF on Canvas](https://psu.instructure.com/files/144517093/download?download_frd=1).
    - Optional [[@Begley2012-cr]](http://dx.doi.org/10.1038/483531a)
- [Class notes](https://psu-psychology.github.io/psych-490-reproducibility-2023-spring-notes/course-intro.html)

### Thursday, January 12 {-}

- How science works (or should)
- Read
    - [@Ritchie2020-fm], Chapter 1. [Alternate link to PDF on Canvas](https://psu.instructure.com/courses/2245007/files/folder/readings?preview=144654645).
    - [[@Nosek2012-al]](http://dx.doi.org/10.1080/1047840X.2012.692215). [Alternate link to PDF on Canvas](https://psu.instructure.com/courses/2245007/files/folder/readings?preview=144654434).
    - Optional [@sagan-1996-baloney], Chapter 12, The Fine Art of Baloney Detection. [PDF on Canvas](https://psu.instructure.com/files/144517092/download?download_frd=1)

---

## January 16 - 20 {- #week-02}

### Tuesday, January 17 {-}

- Scientific norms and counter-norms
- Read
    - [@Merton1973-vf]. [PDF on Canvas](https://psu.instructure.com/files/144517091/download?download_frd=1).
    - [[@Mitroff1974-pp]](https://doi.org/10.2307/2094423).
- [Assignment]{.green_assigned}
    - Complete (anonymous) [survey](https://forms.gle/1zqzfNNXWyCgiDSJ9) on scientific norms and counter-norms. **No write-up**.

### Thursday, January 19 {-}

- Adherence to norms and counter-norms
- Read
    - [[@Kardash2012-kq]](https://doi.org/10.1007/s11251-011-9195-0).
    - [[@Macfarlane2008-tc]](https://doi.org/10.1007/s10805-008-9055-y).
- Skim
    - [[@Anderson2010-rl]](http://dx.doi.org/10.1353/jhe.0.0095).
    - [[@Kim2018-tr]](https://doi.org/10.1177/0971721817744438).
- [Assignment]{.green_assigned}
    - [Exercise 01: Norms and counter-norms write-up](#ex_norms_counternorms)

---

## January 23 - 27 {- #week-03}

### Tuesday, January 24 {-}

- Replication crisis (or not)
- Read
    - [@Ritchie2020-fm], Chapter 2.
    - [[@Begley2012-cr]](http://dx.doi.org/10.1038/483531a)
    - (Optional) [@Oreskes2017], Chapter 7, pp. 228-244.

### Thursday, January 26 {-}

- Replication failure: The "Lady Macbeth Effect"
- Read
    - [[@Zhong2006-nf]](http://dx.doi.org/10.1126/science.1130726)
    - [[@Earp2014-ek]](https://doi.org/10.1080/01973533.2013.856792)
- [Due]{.orange_due}
    - [Exercise 01: Norms and counter-norms write-up](#ex_norms_counternorms)

---

## January 30 - February 3 {- #week-04}

### Tuesday, January 31 {-}

- Replication: Priming effect
- Read
    - [[@Bargh1996-yv]](http://dx.doi.org/10.1037//0022-3514.71.2.230)
    - [[@Doyen2012-ib]](http://dx.doi.org/10.1371/journal.pone.0029081)

### Thursday, February 2 {-}

- Replication in cancer biology
- Read
    - [[@Errington2021-sy]](http://dx.doi.org/10.7554/eLife.71601)
    - [[@Errington2021-dp]](https://doi.org/10.7554/eLife.67995)

---

## February 6 - 10 {- #week-05}

### Tuesday, February 7 {-}

- Reproducibility and replicability reconsidered
- Read
    - [[@baker_1500_2016]](https://doi.org/10.1038/533452a)
    - [[@goodman_what_2016]](https://doi.org/10.1126/scitranslmed.aaf5027)
- Skim
    - [[@Fidler2021-xn]](https://plato.stanford.edu/archives/sum2021/entries/scientific-reproducibility/)

### Thursday, February 9 {-}

- Fraud & misconduct
- Read
    - [@Ritchie2020-fm], Chapter 3
    - [[@Bhattacharjee2013-rw]](https://www.nytimes.com/2013/04/28/magazine/diederik-stapels-audacious-academic-fraud.html)
    - (Skim) [[@Levelt2012-ap]](https://pure.mpg.de/rest/items/item_1569964/component/file_1569966/content)
    - (Skim) [[@Carpenter2012-ot]](https://www.science.org/content/article/harvard-psychology-researcher-committed-fraud-us-investigation-concludes)

---

## February 13 - 17 {- #week-06}

### Tuesday, February 14 {-}

- Retraction and scientific integrity
- Read
    - [[@Brainerd2018-iy]](https://doi.org/10.1126/science.aav8384)
- Explore
    - <https://retractionwatch.com/>
    - <https://ori.hhs.gov/>
- [Assignment]{.green_assigned}
    - [Exercise 02: P-hack your way to scientific glory](#ex_p_hacking)

### Thursday, February 16 {-}

- Questionable research practices
- Read
    - [[@simmons_false-positive_2011]](http://dx.doi.org/10.1177/0956797611417632)
    - [[@John2012-tk]](http://dx.doi.org/10.1177/0956797611430953)
- Watch
    - [[@Ngiam2020-ln]](https://www.youtube.com/watch?v=bf3GqyBRgzY)

---

## February 20 - 24 {- #week-07}

### Tuesday, February 21 {-}

- Bias
- Read
    - [@Ritchie2020-fm], Chapter 4
- [Due]{.orange_due}
    - [Exercise 02: P-hack your way to scientific glory](#ex_p_hacking) write-up.
   
### Thursday, February 23 {-}

- File drawer effect
- Read
    - [[@Rosenthal1979-zi]](https://doi.org/10.1037/0033-2909.86.3.638)
    - [[@Franco2014-yu]](http://dx.doi.org/10.1126/science.1255484)
    
---
    
## February 27 - March 3 {- #week-08}

### Tuesday, February 28 {-}

- Negligence
- Read
    - [@Ritchie2020-fm], Chapter 5
    - [[@Nuijten2015-ul]](https://doi.org/10.3758/s13428-015-0664-2)
    - [[@Szucs2017-fc]](http://dx.doi.org/10.1371/journal.pbio.2000797)
- [Assignment]{.green_assigned}
    - [Exercise 03: Alpha, Power, Effect Sizes, & Sample Size](#ex_apes)

### Thursday, March 2 {-}

- Hype
- Read
    - [@Ritchie2020-fm], Chapter 6
    - [[@Carney2010-gq]](http://dx.doi.org/10.1177/0956797610383437)
    - (Optional) [[@Ranehill2015-dj]](http://dx.doi.org/10.1177/0956797614553946)
- Watch
    - [[@Cuddy2012-zx]](https://www.ted.com/talks/amy_cuddy_your_body_language_may_shape_who_you_are)
- [Due]{.orange_due}
    - [Final project](#final_project) proposal

---

## March 6-10 (Spring Break) {- #spring-break}

**NO CLASS**
    
---

## March 13 - 17 {- #week-09}

#### Tuesday, March 14 {-}

- Solutions
- Read
    - [[@munafo_manifesto_2017]](https://doi.org/10.1038/s41562-016-0021)
    - [[@Begley2013-vm]](http://dx.doi.org/10.1038/497433a)
- [Due]{.orange_due}
    - [Exercise 03: Alpha, Power, Effect Sizes, & Sample Size](#ex_apes) write-up

### Thursday, March 16 {-}

- Changing journal policies
- Read
    - [[@nosek_promoting_2015]](https://doi.org/10.1126/science.aab2374)
    - [[@Gilmore2020-sl]](https://doi.org/10.1111/cdep.12360)
    - [[@Srcd2019-hg]](https://www.srcd.org/policy-scientific-integrity-transparency-and-openness)

---

## March 20 - 24 {- #week-10}

### Tuesday, March 21 {-}

- Large-scale replication studies
- Read
    - [[@collaboration_estimating_2015]](https://doi.org/10.1126/science.aac4716)
    - [[@Camerer2018-tr]](https://doi.org/10.1038/s41562-018-0399-z)
- [Assignment]{.green_assigned}
    - [Exercise 04: Replication](#ex_replication)

### Thursday, March 23 {-}

- Meta-analysis & many analysts
- Read
    - [[@Wilson2014-ol]](https://www.psychologicalscience.org/observer/introduction-to-meta-analysis-a-guide-for-the-novice)
    - [[@Silberzahn2018-st]](https://doi.org/10.1177/2515245917747646)

---

## March 27 - 31 {- #week-11}

### Tuesday, March 28 {-}

- Preregistration
- Read
    - [[@Nosek2018-jk]](http://dx.doi.org/10.1073/pnas.1708274114)
    - [[@Ledgerwood2018-sn]](http://dx.doi.org/10.1073/pnas.1812592115)
    - [[@Goldin-Meadow2016-mc]](https://www.psychologicalscience.org/observer/why-preregistration-makes-me-nervous)
    - [[@Claesen2021-ae]](http://dx.doi.org/10.1098/rsos.211037)
- Explore
    - [clinicaltrials.gov](https://clinicaltrials.gov/)
- [Due]{.orange_due}
    - [Exercise 04: Replication](#ex_replication)
    
### Thursday, March 30 {-}

- Catch-up day

---

## April 3 - 7 {- #week-12}

### Tuesday, April 4 {-}

- Data sharing
- Read
    - [[@Houtkoop2018-tl]](https://doi.org/10.1177/2515245917751886)
    - [[@Tenopir2020-mq]](http://dx.doi.org/10.1371/journal.pone.0229003)

### Thursday, April 6 {-}

- Data sharing II
- Read
    - [[@National_Institutes_of_Health_undated-it]](https://grants.nih.gov/grants/guide/notice-files/NOT-OD-21-013.html)
    - [[@GilmoreAdolph2017]](https://doi.org/10.1038/s41562-017-0128)
    - [[@Meyer2018-vk]](https://doi.org/10.1177/2515245917747656)
- [Assignment]{.green_assigned}
    - [Exercise 05: Data and materials sharing](#ex_data_sharing)

---

## April 10 - 14 {- #week-13}

### Tuesday, April 11 {-}

- Materials, code, & protocol sharing
- Read
    - [[@Soska2021-mh]](http://dx.doi.org/10.7191/jeslib.2021.1208)
    - [[@Gilroy2019-bf]](http://dx.doi.org/10.1007/s40614-019-00202-5)
- Explore
    - [protocols.io](https://www.protocols.io/)
    - [Journal of Visualized Experiments (JOVE)](https://www.jove.com/)

### Thursday, April 13 {-}

- Open science tools
- Read
    - [[@Kathawalla2021-tk]](https://doi.org/10.1525/collabra.18684)
    - [[@Cruwell2019-nz]](https://doi.org/10.1027/2151-2604/a000387)
- [Due]{.orange_due}
    - [Exercise 05: Data and materials sharing](#ex_data_sharing)

---

## April 17 - 21 {- #week-14}

### Tuesday, April 18 {-}

- Open science tools II

### Thursday, April 20 {-}

- Project work day

---

## April 24 - 28 {- #week-15}

### Tuesday, April 25 {-}

- Project presentations

### Thursday, April 27 {-}

- Project presentations

---
    
## May 1-5 {- #finals-week}

### Wednesday, May 3 {-}

- [Due]{.orange_due}
  - [Final project]{#final_project} write-ups due 5:00 PM.