# Resources {-}

Most of the readings for the course will come from the published scientific literature.

## Required Text {-}

We will make extensive use of the following book:

Ritchie, S. (2021). *Science Fictions: Exposing Fraud, Bias, Negligence, and Hype in Science*. Penguin Random House. 

This book is **required** for the course.

## Other readings

Scanned copies of other readings are available as PDFs on [Canvas](https://psu.instructure.com/courses/2245007/files/folder/readings).

## Web-based resources {-}

- [Glossary](https://forrt.org/glossary/) of open science terms by the [Framework for Open and Reproducible Research Training (FORT)](https://fort.org). [[@Parsons2022-rs]](http://dx.doi.org/10.1038/s41562-021-01269-4).
- [[@Nordmann_undated-kd]](https://psyteachr.github.io/) site and its set of web-books on data analysis, visualization, and reproducible research.
- [[@The_Turing_Way_undated-fk]](https://the-turing-way.netlify.app/reproducible-research/open.html), a web book about open research practices
- [[@Ball2015-fv]](https://osf.io/vkhbt/), a collection of course syllabi for open and reproducible methods.