# Exercise 02: The road to scientific glory {#ex_p_hacking -}

## Dates {-}

Due: [Tuesday, February 21, 2023]{.orange_due}.

## Acknowledgment {-}

This exercise builds heavily on [[@Pownall2021-aa]](https://doi.org/10.17605/OSF.IO/TH254).

## Goals {-}

This exercise aims to build your understanding about [*p-hacking*](https://forrt.org/glossary/p-hacking/), what it is, how it can occur, and its impact on research.

## Materials {-}

- a computer, tablet, or smartphone with access to the internet.
- a means of keeping brief notes (notebook or text/word processing document).

## Background {-}

You are a policy analyst with a not-for-profit, or as our resource says, "You’re a social scientist with a hunch: The U.S. economy is affected by whether Republicans or Democrats are in office."
Your task is to publish a short report about whether the U.S. economy does better under Republican control or Democratic control.
You probably have prior ideas about this question, but your goal is to provide *data* that answer it.

You will make use of a [dataset](https://projects.fivethirtyeight.com/p-hacking/) with information about how well the U.S. economy performs and about the degree of Republican or Democratic political power.
The dataset goes back to 1948.

## Your analysis {-}

1. Choose a party as the focus of your report (Republican or Democratic).
2. Write down your prior hypothesis about whether the economy does better or worse under Republican or Democratic control. Do this before you visit the web site[^1].

[ ] Republican</br>
[ ] Democratic

[ ] Economy does better</br>
[ ] Economy does worse

3. Visit the [dataset](https://projects.fivethirtyeight.com/p-hacking/) site.
4. Select the party you have chosen to focus on by pressing the button in panel 1. of the site.
5. Write down the variables that are selected in "2. Define Terms" on the site.
    - Politicians included
        - [ ] Presidents
        - [ ] Governors
        - [ ] Senators
        - [ ] Representatives
    - Measure(s) of economic performance
        - [ ] Employment
        - [ ] Inflation
        - [ ] GDP
        - [ ] Stock prices
    - Other options
        - [ ] Factor in power
        - [ ] Exclude recessions

6. If you know how, take a screenshot of the plot in "3. Is there a relationship" Include the screenshot in your report. In a sentence or two, describe what the plot shows.
7. Report the result indicated in "4. Is your result significant?". What is the *p*-value? What does that p-value mean in practical terms--what question was tested[^2]? Is your result "publishable"?
8. Select another set of variables (politicians included, measures of economic performance, or other options). Record the variables you chose, your prediction, and the outcome. Did the result change (the *p*-value of the test; whether it's 'publishable' or not)? 
9. You may continue to explore other combinations of variables if you so choose. For each set of variables you select, write down the variables you selected and the *p*-value you found.

Here is a table you can use as a template to format your data.

| Analysis number | Politicians Included | Economic Measures | Other factors | p-value |
|---------------- |-----|-------------------|---------------|---------|
| 1               | <your data>          | <your data>       |   <your data> |   <your data> |
| 2               | <your data>          | <your data>       |   <your data> |   <your data> |
| ...             | <your data>          | <your data>       |   <your data> |   <your data> |

10. Please enter your data into [this](https://docs.google.com/forms/d/e/1FAIpQLSegZX1IgaD993bGxA7w0Gk9D_nj30f3XFPylVYK110_s51MQw/viewform?usp=sf_link) Google form. Create a new form entry for each row of the above table. We'll look at the (anonymized) data from you and your classmates in class to see if there are any patterns to the findings.

11. Create a report that captures the information you collected during the exercise and summarizes the overarching implications of your findings in a few sentences. 
For example, did you find yourself *p*-hacking to get a result you predicted or did you stop once you got a result that satisfied you?
How confident are you that the variables you chose are the right ones?
If another data analyst picked other variables and came to a different conclusion about which party is better (or worse) for the economy, would that change your mind?
What are the larger-scale implications of *p*-hacking for scientific research?

You may use the simple [report template](report_template.html) as a guide. 

## Submit {-}

Please save a copy of your report as a docx using the preferred file naming convention for this class: `lastname-firstname-PSYCH490.002-ex02.docx`, where you substitute your last name for `lastname` and your first name for `firstname`.

Submit your report on Canvas in the dropbox for this assignment.

Please also bring a copy to class with you on **February 21, 2023**.

---

[^1]: Think about why we want you to write down your prediction before you look at the dataset.
[^2]: **Hint**: The question tested has to do with the slope of the plot in 3. 